os:
  - linux

language: php

php:
  - '7.1'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - cp phpunit.xml.travis phpunit.xml
script:
  - vendor/bin/phpunit --coverage-text
  
